# Ansible Inventory File
# Generated by Terraform
# Private IPs are used for internal communication

[jenkins]
jenkins ansible_host=${jenkins_ip}

[sonarqube]
sonarqube ansible_host=${sonarqube_ip}

[nexus]
nexus ansible_host=${nexus_ip} ansible_public_ip=${nexus_public_ip}

[app_servers]
app_server ansible_host=${app_server_ip} ansible_public_ip=${app_server_public_ip}

[ansible_slaves]
ansible_slave ansible_host=${ansible_slave_ip} ansible_public_ip=${ansible_slave_public_ip}

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/ubuntu/.ssh/ansible_key

# Nexus configuration
nexus_url=http://${nexus_ip}:8081
nexus_public_url=http://${nexus_public_ip}:8081
